language: ruby
sudo: false
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - jruby-9.1.9.0
gemfile:
  - gemfiles/ar51.gemfile
  - gemfiles/ar52.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.1.9.0
addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
before_script:
  - psql -U postgres -c "create database postgis_adapter_test"
  - psql -U postgres -d postgis_adapter_test -c "create extension postgis"
script: bundle exec rake test
before_install:
  - gem update --system
  - gem install bundler
